import time
import math
print('MTU_GIS_MATH_4.22')
a=float(input('a='))
b=float(input('b='))
c=float(input('c='))
d=float(input('d='))
time_a1=float(input('time_a1='))
time_a2=float(input('time_a2='))
time_b1=float(input('time_b1='))
time_b2=float(input('time_b2='))
print('Processed...')
for i in range (1,221,11):
    rt_1=float(math.cos(a*b*c*d)/i*time_b2)
    rt_2=float(math.cos(a/b/c/d)/i*time_b2)
    time_cv_1=float(time_a1**2+time_a2**2/(rt_2*i**2))
    time_fcv_1=float(time_cv_1/time_b1/i)*math.cos(rt_1)
    print('__________')
    print (i,rt_1,rt_2,time_cv_1,time_fcv_1)
    time.sleep(2)
    print ('next...')
print ('End summary...')
print ('N= ',rt_1+rt_2)
print ('Press Enter for exit')
input()
